name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t piran94/new-webapp:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image to Docker Hub
        run: docker push piran94/new-webapp:latest

      - name: Pull the Docker image to Docker Desktop
        run: docker pull piran94/new-webapp:latest

