name: Build, Push, and Run Docker Image on Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t piran94/new-webapp:latest -f Dockerfile .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image to Docker Hub
        run: docker push piran94/new-webapp:latest

      - name: Run the Docker container
        run: docker run -d -p 8090:80 piran94/new-webapp:latest
