name: CI

on:
  push:
    branches:
      - master

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Modify the following line to use the "gitActionPractice" directory
      - name: Build the Docker image
        run: docker build --file gitActionPractice/Dockerfile --tag webapp:latest gitActionPractice

