name: CI

on:
  push:
    branches:
      - master

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t webapp:latest -t webapp:${{ github.sha }} .



